### ISSUE TITLE
Is it possible to use 'expand' parameters?

### ISSUE THREAD

**Issue by JoeWesthead** [cpliakas/jira-client#10]
Looking at the [REST API docs](https://bunjil.jira-dev.com/plugins/servlet/restbrowser#/resource/api-2-issue-issueidorkey), it seems as if you can add extra parameters to the **issue** call, for example: 

`/jira/rest/api/2/issue/JIRA-1234?expand=changelog`.

Looking through the pleasant code in this repo, I can't find any explicit reference to these parameters. If have tried:
`$issue = $jira->issue('JIRA-1234?expand=changelog')->get();`

This however throws errors that "This issue does not exist" (though without 'expand' it works fine). Am I missing something rather obvious here or is it just not included here?

**Comment by cpliakas** [comment]
Unfortunately this client consumes the SOAP API, so that is likely why you are getting errors. At the time this library was created, the REST API was very immature and only contained a fraction of what the SOAP API provided. My guess is that has changes in the last couple of years.

**Comment by JoeWesthead** [comment]
Fair enough. Thanks for the quick reply, saved me time bashing my head. I'll close this for now if that's not something on the horizon.

**Comment by cpliakas** [comment]
Sorry, unfortunately it is not :-(. There are some pretty good JIRA clients around the REST API that are emerging, though, so hopefully this library can be deprecated in favor of one such client. If you come across any, please feel free to post back so that developers are directed to a project that best fits their needs.

Thanks for posting,
Chris
